### ISSUE TITLE
The provisioning engine does not export list specific content type

### ISSUE THREAD

**Issue by stevebeauge** [pnp/PnP-Sites-Core#1457]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
The engine should support list local content types customization. Especially, fields created locally in a list and added to a content type should be exported.

#### Observed Behavior
List specific content types are ignored. Probably, this a missing feature of the provisioning schema.

#### Steps to Reproduce
1. Create a site content type `My content type`, inheriting `Element`
1. Create a list `MyList` based on a generic list
1. Enable content types on the list
1. Add `My content type` to the list
1. Create a field `MyField` **in the list** (no site column). Uncheck `Add to all content types`
1. Edit the **list** content type `My content type` (not the site content type)
1. Add the field `MyField` to the content type
        > At this point, the list settings show the field `MyField` as referenced in `MyContentType`
1. Export the provisioning template (Fields,ContentTypes and Lists handlers are enough)
        > there's no mention of `MyField` referenced to `MyContentType`

**Comment by ruslanurban** [comment]
Also, there are cases when you need to display a different label in the "New Document" menu. Creating a list-level content type would facilitate this requirement.

**Comment by Crispify** [comment]
Any work on this done already? I'm working with BDC fields (External Data) that cannot live on site collection level, so I'm adding it on library level and adding it to some of the content types on library level. The schema currently has no way of specifying this situation and when cloning the site, it leaves the BDC field disconnected of all content types.

**Comment by jonathaneckman** [comment]
+1 but for SharePoint Online.

**Comment by hasannaqvi83** [comment]
Any update on this ?

I recently have noticed that PE doesn't facilitate adding fields to content types local to a list.

**Comment by stevebeauge** [comment]
Unfortunately, nothing has been done for that (as far as I known).

I guess the issue won't be solved, because it would require fixing the schema first then perform a deep rewrite of core handlers. The team behind the project is clearly under effective to handle the increasing number of issues and submitted PR. I wouldn't bet on a resolution.

**Comment by userings** [comment]
+1 for SharePoint 2016

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, we are not going to change the engine in order to support the requested scenario. In fact, as a best practice, we do not encourage creating fields at list-level and attaching them to local content types of that list. We rather suggest defining content types at site-level and associate site columns to them. Moreover, the required changes (schema and engine) are too heavy compared with the benefits of the suggested change. As such, we will not release any fix to this behavior and I'm going to close this issue. Thanks for using the PnP Provisioning Engine.
