### ISSUE TITLE
Include custom field values for modern pages by default when using -IncludeAllClientSidePages

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/PnP-Sites-Core#2338]
#### Category
- [ ] Bug
- [x] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

#### Use case
Consider the following setup:
* SitePages library with modern pages
* a custom field has been added to the SitePages libraries, say _News Category_
* _News Category_ contains a value for every page

Now I want to:
* export all client side pages as template (using the `-IncludeAllClientSidePages` parameter)
* apply this template to another site

#### Expected or Desired Behavior
I expected all client side pages to have the correct value set in their respective _News Category_ field.

#### Observed Behavior
The value is not included in the template. The default value for the field is set rather than the correct one.

#### Steps to Reproduce
* create a site
* add a field _FIELD_ to the SitePages library
* create some pages and enter non-default field values into _FIELD_
* export site as template using the `-IncludeAllClientSidePages` parameter
* apply the template to a new site

Values of FIELD are not present.

#### Notes
I tried to add the field values to the template to check if this already covers this scenario but the command failed me.

This is the command I used:

`Add-PnPDataRowsToProvisioningTemplate -Path "template.xml" -List "Websiteseiten" -Fields "News_x0020_Kategorie"`

The values are properly added to the template. Currently #2337 is preventing me from testing if this works. My assumption is: No.

**Comment by heinrich-ulbricht** [comment]
After fixing #2337 (pull request pending) I now get another error:

"Additions to this Web site have been blocked.\n\nPlease contact the administrator to resolve this problem."

Google says it might be related to the `UpdateOverwriteVersion` call.
https://github.com/SharePoint/PnP-Sites-Core/blob/9916b74d78a256fb654f4273287e4d5b2ed66687/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs#L517

**Comment by heinrich-ulbricht** [comment]
With the two pending pull requests https://github.com/SharePoint/PnP-Sites-Core/pull/2341 and https://github.com/SharePoint/PnP-Sites-Core/pull/2344 the way is at least cleared for a workaround:

* export client side pages to template A
* export SitePages lib to template B
* use Add-PnPDataRowsToProvisioningTemplate to add field values of SitePages lib to template B
* add KeyColumn="FileLeafRef" to template B to trigger "Update" behavior
* provision new site using template A - this provisions the client side pages
* provision template B - this provisions field values for the pages

Blog post incoming.

**Comment by tarjeieo** [comment]
This is also relevant to me - did you blog about this @heinrich-ulbricht ?

**Comment by heinrich-ulbricht** [comment]
@tarjeieo Yes! Here it is: https://www.linkedin.com/pulse/inside-pnp-09-include-modern-page-properties-heinrich-ulbricht/

**Comment by phillipharding** [comment]
I know this issue is closed, but in this scenario I've used the ```<pnp:FieldValues />``` element with some success.
https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2020-02.md#baseclientsidepage

The template when exported doesn't include the page field values as you point out, but adding a ```<pnp:FieldValues />``` section to each page in the template has worked quite well.
