### ISSUE TITLE
Apply-PnPProvisioningTemplate: Additions to this Web site have been blocked

### ISSUE THREAD

**Issue by msgx** [pnp/PnP-Sites-Core#2454]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
`Apply-PnPProvisioningTemplate` is completed successfully, PnP template is applied to the target site collection, files are uploaded and updated with properties specified.

#### Observed Behavior
`Apply-PnPProvisioningTemplate` just stopped working with specific `<pnp:File>` instructions after upgrading PnP PowerShell from version **3.13**.1909.0 to version **3.14**.1910.0. The following exception appears:

```
Apply-PnPProvisioningTemplate : Additions to this Web site have been blocked.
Please contact the administrator to resolve this problem.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path ".\path\to\template.xml...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
  + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
```

#### Steps to Reproduce
1. Upgrade PnP PowerShell to version 3.14.1910.0.
2. Create a provisioning template which uploads a page to a library with versioning enabled, e.g. add a page layout to master page gallery.
3. Add some properties to the page via `<pnp:Properties>` (see example below).
4. Connect to the target site collection and try to apply the template via Apply-PnPProvisioningTemplate.

#### Template Example
```xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/09/ProvisioningSchema">
  <pnp:Preferences />
  <pnp:Templates>
    <pnp:ProvisioningTemplate ID="TEMPLATE-SAMPLE" Version="1" BaseSiteTemplate="STS#0">
      <pnp:Files>
        <pnp:File Src="mysimple.aspx" Folder="{sitecollection}/_catalogs/masterpage" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="Title" Value="My Simple Page Layout" />
            <!-- other properties -->
          </pnp:Properties>
        </pnp:File>
      </pnp:Files>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```
You can also use this **[gist](https://gist.github.com/msgx/615b6518019e3ea0ac0ce9ab64ae91a0)** if you prefer.

#### Notes
* The error disappears when `<pnp:Properties>` removed from `<pnp:File>`.
* Also, I figured out that turning off versioning from the target library eliminates the error.
* We can also get rid of the error by allowing major versions only in the library.

P.S. Linked issue: **#2438**, thanks to @SBajonczak

**Comment by sid1260** [comment]
We are facing the same issue. Can you let us know where you stand regarding this issue?

**Comment by franelj** [comment]
Same here.

**Comment by YoussefMoumen** [comment]
I've got the same issue.

**Comment by rajajii** [comment]
Same problem here

**Comment by Fabske411** [comment]
Same problem here. Does somebody have a solution for this?

**Comment by franelj** [comment]
On my side, I had to revert the package version back to an old version (3.9.1905.1). Not the best solution but it worked.
I didn't try it yet, but as there were two new releases of the package since this bug was opened, maybe you can try to upgrade your package to a newer version, if you didn't do it already ?

**Comment by SBajonczak** [comment]
According to the hint "We can also get rid of the error by allowing major versions only in the library".. I tried in my site to fix it with this issue. But this didn't work.

**Comment by PeterHeibrink** [comment]
Any idea when the triage will take place? I still face the same issue with the latest package.

**Comment by msgx** [comment]
Seems like PnP PowerShell **3.20.2004.0** does not have this issue.

**Comment by chrriedel** [comment]
Had the same issue today. It seams like the issue is because the provisioning engine wants to make changes by updating properties direkt to the major version of the file and SharePoint doesn't allow this. 
You can work arround it by first uploading the file as draft and then publish it without overwriting the file. 
The snippet in the template looks like this:
<pnp:File Src="Files\word.docx" Folder="Folder" Overwrite="true" Level="Draft" >
          <pnp:Properties>
            <pnp:Property Key="ContentType" Value="{contenttypeid:ContentType}" />
            <pnp:Property Key="Title" Value="{parameter:Name}" /> 
            <pnp:Property Key="Projectname" Value="{parameter:Name}"/>
            <pnp:Property Key="Description" Value="{parameter:Description}"/> 
            <pnp:Property Key="Status" Value="green"/>
          </pnp:Properties>
        </pnp:File>
         <pnp:File Src="Files\word.docx" Folder="Folder" Overwrite="false" Level="Published" />

That worked on my site.
