### ISSUE TITLE
Get-PnPProvisioningTemplate - the page is not a valid client side page

### ISSUE THREAD

**Issue by kylepdx** [pnp/PnP-Sites-Core#2472]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

SharePointPnPPowerShellOnline 3.14.1910.1

#### Expected or Desired Behavior
Get-PnPProvisioningTemplate -Out c:\extract.pnp -IncludeAllClientSidePages -Handlers Pages,PageContents 

should extract all client side pages. 

#### Observed Behavior
PnPTrace logs shows following errors: 

PowerShell_ISE.exe Error: 0 : 2019-10-29 21:01:23.6878	[Provisioning]	[0]	[Error]	Error occured while retrieving basetemplate	

PowerShell_ISE.exe Warning: 0 : 2019-10-29 20:37:35.2150	[Client Side Page Contents]	[17]	[Information]	This page is not a valid client side page and can't be extracted. Underlying error = Page /SitePages/Home.aspx does not exist in current web.	

PowerShell_ISE.exe Warning: 0 : 2019-10-29 20:37:35.6107	[Client Side Page Contents]	[17]	[Information]	This page is not a valid client side page and can't be extracted. Underlying error = Page /SitePages/Training.aspx does not exist in current web.	

PowerShell_ISE.exe Warning: 0 : 2019-10-29 20:37:35.9816	[Client Side Page Contents]	[17]	[Information]	This page is not a valid client side page and can't be extracted. Underlying error = Page /SitePages/Locations.aspx does not exist in current web.	

Pages are there and render fine.  I can run the following commands with no errors:  

Get-PnPListItem -List "SitePages"    # returns list of all pages on the site as expected 

Get-PnPFile -Url "/SitePages/home.aspx" -Path c:\temp -AsFile    #downloads the file

#### Steps to Reproduce

Note:  This site was created as a communication site and was swapped into the root site collection using Invoke-SPOSiteSwap.  

Get-PnPProvisioningTemplate -Out c:\extract.pnp -IncludeAllClientSidePages -Handlers Pages,PageContents

**Comment by XopherDesign** [comment]
I'm having the same issue with my communication site. I tried older versions of PnP ("3.13.1909.0", "3.12.1908.1", "3.10.1906.0") same issue. Have you found any work arounds @kylepdx ?

**Comment by mchip88** [comment]
Not sure if this helps but I tried the commands on a non-root site and they worked fine 

eg.  /sites/test-site

**Comment by Chitra-Dharaiya** [comment]
I am facing the same issue with Root Modern Team Site. 
Default tenant had provided Communication Site as Root Site. 
Used Invoke-SPOSiteSwap to swap the Root site to Modern Team Site.
Having the latest version of PnP - 5.1.17763.771. 
Pages are not coming in while extracting as template including -IncludeAllClientSidePages parameter while extracting.

**Comment by sharepointcraft** [comment]
Same issue for me, too.
