### ISSUE TITLE
ExecuteQueryRetryAsync for on-premise SharePoint

### ISSUE THREAD

**Issue by poke** [pnp/PnP-Sites-Core#2545]
**Category:** Enhancement
**Environment:** SharePoint Server 2019 (on-premise)

I noticed that [`ClientContextExtensions.ExecuteQueryRetryAsync`](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs#L74) exists as an extension method which provides an asynchronous alternative to the synchronous `ExecuteQueryRetry` extension method.

Unfortunately, this method appears to be absent from the on-premise version of PnP. Is there a reason for this?

The SharePoint CSOM library `SharePoint.Client` _does_ support asynchronous requests using the [`ClientContext.ExecuteQueryAsync` method](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt829503(v=office.15)). And looking through the IL, I could see that it indeed does call the internal `SPWebRequestExecutor.ExecuteAsync` which uses [`WebRequest.GetResponseAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.getresponseasync?view=netframework-4.8). So there is an actual asynchronous call being made for SP 2019.

This means that the `ExecuteQueryRetryAsync` extension method could easily use the SP Online behavior here and default to asynchronous execution.

Is there a reason on-premise SharePoint is being explicitly excluded or is this just legacy from times where it was not supported? Is there a way we could remedy this for SP 2019?

**Comment by lemonpowah** [comment]
I second this. I also want to move to SharePoint Online however some customers are still required to have their SharePoint installation OnPremise. The ExecuteQueryRetryAsync method would greatly help us.

**Comment by poke** [comment]
As I had to learn the hard way through #1892, `ExecuteQueryRetry` doesn’t actually do anything when targeting on-premise CSOM versions since they only were able to fix the method to do its job after the SPO CSOM version was patched.

So at this point, I strongly suggest anyone targeting SharePoint Server not to use `ExecuteQueryRetry` since its name makes a promise that it doesn’t actually hold. If you need a retry mechanism, you will have to do it yourself and manually re-add any query that you wanted to execute.

Since the on-premise CSOM will likely never change, and with these PnP libraries being sunsetted by the end of the year, I don’t see a reason to follow this request any more.
