### ISSUE TITLE
Provisioning Template.  Omitting Sharing Settings results is default being Disabled

### ISSUE THREAD

**Issue by SteveClements** [pnp/PnP-Sites-Core#2595]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Provisioning Schema: 202002

#### Description
When using the Provisioning Template, I'm using Tenant Template, probably applies to any as it's related to Tenant config.
If you don't specify `<pnp:SharingSettings>` in the XML file, the type resolver sets the default value to 'Disabled' rather than null.

#### Expected or Desired Behavior
Sharing Settings should not be changed at all if `SharingSettings `is not specified in the template.

#### Observed Behavior
All Sharing Settings in the Tenant are removed and set to Disabled.

#### Steps to Reproduce
1. Ensure sharing settings in the Tenant are not Disabled.
2. Create a tenant template with a `<pnp:Tenant>` section
3. Do not specify `SharingSettings`
4. Run the template
5. Check sharing settings in the tenant, they will be Disabled.

#### Fix
I've fixed this is a local build of pnp core by changing
`OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.Resolvers.V202002.SharingSettingsFromSchemaToModel`

Resolve will return null if `SharingSettings `are null, rather than a default instance of `Model.SharingSettings`, which has an `enum `where `0 = Disabled`.

I will try and create a clean branch and submit a PR.  But in the meantime, are there any potential issues with this fix?  It seems to be expected as 
`TenantHelper.ProcessSharingSettings` is checking for `null `and doing nothing (as expected) if it is.

**Comment by jansenbe** [comment]
change was merged
