### ISSUE TITLE
ZoneEmphasis parameter not working in Add-PnPClientSidePageSection

### ISSUE THREAD

**Issue by Rafaelki** [pnp/PnP-Sites-Core#2637]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
As @kadu-jr pointed in issue #4044 of the office-docs-powershell repository (https://github.com/MicrosoftDocs/office-docs-powershell/issues/4044): 
When using the Add-PnPClientSidePageSection command, the -ZoneEmphasis parameter does not work, No matter what value I set between 0 and 3, the new page section always comes out without background.
Looks like this was fixed for Apply-PnPProvisioningTemplate in #2401, but not for Add-PnPClientSidePageSection.

**Comment by kadu-jr** [comment]
Hi @Rafaelki,

Which version of the PnP-Powershell are you using? I just updated to the latest version - 3.20.2004.0 - and the -ZoneEmphasis parameter is working as expected in the Add-PnPClientSidePageSection command.

**Comment by Rafaelki** [comment]
Hi @kadu-jr , I am so sorry, you are right, it is working. Thanks for your quick answer.
My confusion was because I was adding a webpart in -Section 1 -Column 1, but section 1 was the section that exists by default, no the new one.
