### ISSUE TITLE
[BUG] Cannot instantiate the default list webpart

### ISSUE THREAD

**Issue by yborghmans** [pnp/PnP-Sites-Core#2779]
#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Instantiation of the default list webpart on a modern page.

#### Observed Behavior
On a specific tenant the code suddenly stopped working. The same code was already running for more than 6 months, and is still working correctly on other tenants.

#### Steps to Reproduce
var modernPage = ClientSidePage.Load(clientContext, "name.aspx");
var listWebPart = modernPage.InstantiateDefaultWebPart(DefaultClientSideWebParts.List); => this returns null

**Comment by jansenbe** [comment]
Doing some quick research shows that the call to _api/web/getclientsidewebparts we do does not return the list web part anymore. I've started an internal thread to understand why this is happening.

**Comment by Ganesh-Rajagopal** [comment]
Please check and help us as soon as poosible

**Comment by bmoyer23** [comment]
thanks @jansenbe 

Would this also affect the Apply-PnPProvisioningTemplate command? We are missing our list web parts on site pages when creating sites from template

**Comment by salascz** [comment]
thanks @jansenbe 

@bmoyer23 yes, the Apply-PnPProvisioningTemplate command is affected. There is a Warning in log file:

> Could not find the control with either ID = f92bf067-bc19-489e-a556-7fe95f508720 or Name =  to install. Did you install your client side web part to this site?

The f92bf067-bc19-489e-a556-7fe95f508720 identifier was previously used for default List WebPart

**Comment by ARAZA-URBIS** [comment]
There are two new web parts introduced by them:

**ListDocumentLayout** with **Id**: c6eb85d4-7fd2-4938-bfb8-5a899344ee86
**DocLibWebPart**  with **Id**:  6ee6fe3d-ed5f-4c42-b663-b1df52a8ae3b

Probably you need to add them in your DefaultClientSideWebParts enumeration

I tried adding them but the web parts were giving error once added.  Probably was missing something

Moreover, the **workbench.aspx** page also does not list the two **List**, **Document Library** web part anymore.  So something is definitely wrong

**Comment by jansenbe** [comment]
@ARAZA-URBIS : thanks for the additional details.

We're still investigating, will provide an update soon.

**Comment by jansenbe** [comment]
The root cause of the problem has been found and a fix is rolling out soon.

**Comment by yborghmans** [comment]
It is indeed working again. Many thanks @jansenbe (and the rest of the team).

**Comment by yborghmans** [comment]
@jansenbe 
Any idea why the drag and drop functionality of the webpart isn't working anymore?
And there is also the icon of empty folder..

![image](https://user-images.githubusercontent.com/14016197/94818287-3aeb2e80-03fe-11eb-9f90-45f7fab5dfbb.png)

**Comment by jansenbe** [comment]
@YannickRe : can you create a new issue for this in sp-dev-docs repo?

**Comment by YannickRe** [comment]
@jansenbe not me, but @yborghmans ;)

**Comment by yborghmans** [comment]
@jansenbe for now the (new) problem has been gone away 👍 
And again, many thx for solving the initial problem!
